# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
vehiculesBrands = Vehicule.create([
    {brand: 'ABARTH', model: '500C' },
    {brand: 'ABARTH', model: '500' },
    {brand: 'ALFA ROMEO', model: 'Giulietta' },
    {brand: 'ALFA ROMEO', model: 'MiTo' },
    {brand: 'ALFA ROMEO', model: '4C' },
    {brand: 'ALFA ROMEO (FIAT)', model: '4C' },
    {brand: 'ASTON MARTIN', model: 'DB9' },
    {brand: 'ASTON MARTIN', model: 'Vantage V8' },
    {brand: 'ASTON MARTIN', model: 'Vanquish' },
    {brand: 'ASTON MARTIN', model: 'Vantage V12' },
    {brand: 'ASTON MARTIN', model: 'Rapide' },
    {brand: 'AUDI', model: 'A4' },
    {brand: 'AUDI', model: 'A8' },
    {brand: 'AUDI', model: 'A3' },
    {brand: 'AUDI', model: 'TT' },
    {brand: 'AUDI', model: 'A5' },
    {brand: 'AUDI', model: 'A4 Allroad Quattro' },
    {brand: 'AUDI', model: 'A6' },
    {brand: 'AUDI', model: 'A7' },
    {brand: 'AUDI', model: 'Q3' },
    {brand: 'AUDI', model: 'Q5' },
    {brand: 'AUDI', model: 'S5' },
    {brand: 'AUDI', model: 'A1' },
    {brand: 'AUDI', model: 'A6 Allroad Quattro' },
    {brand: 'AUDI', model: 'S7' },
    {brand: 'AUDI', model: 'S6' },
    {brand: 'AUDI', model: 'S8' },
    {brand: 'AUDI', model: 'RS4' },
    {brand: 'AUDI', model: 'RS5' },
    {brand: 'AUDI', model: 'R8' },
    {brand: 'AUDI', model: 'SQ5' },
    {brand: 'AUDI', model: 'Q7' },
    {brand: 'AUDI', model: 'RS6' },
    {brand: 'AUDI', model: 'RS7' },
    {brand: 'AUDI', model: 'RS Q3' },
    {brand: 'AUDI', model: 'S3' },
    {brand: 'AUDI', model: 'S1' },
    {brand: 'AUDI', model: 'TTS' },
    {brand: 'AUDI', model: 'S4' },
    {brand: 'AUDI', model: 'RS3' },
    {brand: 'BENTLEY', model: 'Continental GT' },
    {brand: 'BENTLEY', model: 'Mulsanne' },
    {brand: 'BENTLEY', model: 'Flying Spur' },
    {brand: 'BENTLEY', model: 'Continental GTC' },
    {brand: 'BMW', model: 'Serie 3' },
    {brand: 'BMW', model: 'Serie 5' },
    {brand: 'BMW', model: 'Serie 4' },
    {brand: 'BMW', model: 'Serie 7' },
    {brand: 'BMW', model: 'Z4' },
    {brand: 'BMW', model: 'X5' },
    {brand: 'BMW', model: 'Serie 1' },
    {brand: 'BMW', model: 'X3' },
    {brand: 'BMW', model: 'Serie 6' },
    {brand: 'BMW', model: 'X1' },
    {brand: 'BMW', model: 'X6' },
    {brand: 'BMW', model: 'I3' },
    {brand: 'BMW', model: 'Serie 2' },
    {brand: 'BMW', model: 'X4' },
    {brand: 'BMW', model: 'I8' },
    {brand: 'BMW', model: 'Serie 2 Gran Tourer' },
    {brand: 'BMW', model: 'Serie 2 Active Tourer' },
    {brand: 'BYD', model: 'E6' },
    {brand: 'CHEVROLET', model: 'Cruze' },
    {brand: 'CHEVROLET', model: 'Aveo' },
    {brand: 'CHEVROLET', model: 'Trax' },
    {brand: 'CHEVROLET', model: 'Orlando' },
    {brand: 'CHEVROLET', model: 'Spark' },
    {brand: 'CHEVROLET', model: 'Camaro' },
    {brand: 'CITROEN', model: 'C4' },
    {brand: 'CITROEN', model: 'C3' },
    {brand: 'CITROEN', model: 'C5' },
    {brand: 'CITROEN', model: 'C3 Picasso' },
    {brand: 'CITROEN', model: 'C4 Picasso' },
    {brand: 'CITROEN', model: 'Grand C4 Picasso' },
    {brand: 'CITROEN', model: 'C4 Aircross' },
    {brand: 'CITROEN', model: 'Nemo' },
    {brand: 'CITROEN', model: 'Berlingo' },
    {brand: 'CITROEN', model: 'C-Elysée' },
    {brand: 'CITROEN', model: 'C4 Cactus' },
    {brand: 'CITROEN', model: 'C1' },
    {brand: 'CITROEN', model: 'C-Zero' },
    {brand: 'CITROEN', model: 'C-Elysée' },
    {brand: 'DACIA', model: 'Logan' },
    {brand: 'DACIA', model: 'Lodgy' },
    {brand: 'DACIA', model: 'Sandero' },
    {brand: 'DACIA', model: 'Duster' },
    {brand: 'DACIA', model: 'Dokker' },
    {brand: 'DFSK', model: 'Serie V' },
    {brand: 'DFSK', model: 'Serie K' },
    {brand: 'DS', model: 'DS 4' },
    {brand: 'DS', model: 'DS 5' },
    {brand: 'DS', model: 'DS 3' },
    {brand: 'FERRARI', model: 'FF' },
    {brand: 'FERRARI', model: 'F12' },
    {brand: 'FERRARI', model: 'California' },
    {brand: 'FIAT', model: 'Freemont' },
    {brand: 'FIAT', model: 'Doblo' },
    {brand: 'FIAT', model: 'Punto' },
    {brand: 'FIAT', model: 'Panda' },
    {brand: 'FIAT', model: '500' },
    {brand: 'FIAT', model: '500L' },
    {brand: 'FIAT', model: '500X' },
    {brand: 'FIAT', model: 'Qubo' },
    {brand: 'FIAT', model: 'Fiorino' },
    {brand: 'FIAT', model: 'Bravo' },
    {brand: 'FIAT (FIAT)', model: 'Bravo' },
    {brand: 'FIAT (FIAT)', model: 'Fiorino' },
    {brand: 'FORD', model: 'C-Max' },
    {brand: 'FORD', model: 'Fiesta' },
    {brand: 'FORD', model: 'FOcus' },
    {brand: 'FORD', model: 'Mondeo' },
    {brand: 'FORD', model: 'Ka' },
    {brand: 'FORD', model: 'S-MAX' },
    {brand: 'FORD', model: 'B-MAX' },
    {brand: 'FORD', model: 'Grand C-MAX' },
    {brand: 'FORD', model: 'Tourneo Custom' },
    {brand: 'FORD', model: 'Kuga' },
    {brand: 'FORD', model: 'Galaxy' },
    {brand: 'FORD', model: 'Grand Tourneo Connect' },
    {brand: 'FORD', model: 'Tourneo Connect' },
    {brand: 'FORD', model: 'EcoSport' },
    {brand: 'FORD', model: 'Tourneo Courier' },
    {brand: 'FORD', model: 'Mustang' },
    {brand: 'FORD', model: 'Transit Connect' },
    {brand: 'HONDA', model: 'Accord' },
    {brand: 'HONDA', model: 'Jazz' },
    {brand: 'HONDA', model: 'Civic' },
    {brand: 'HONDA', model: 'CR-V' },
    {brand: 'HYUNDAI', model: 'I20' },
    {brand: 'HYUNDAI', model: 'Ix35' },
    {brand: 'HYUNDAI', model: 'Ix20' },
    {brand: 'HYUNDAI', model: 'I10' },
    {brand: 'HYUNDAI', model: 'Santa Fe' },
    {brand: 'HYUNDAI', model: 'Veloster' },
    {brand: 'HYUNDAI', model: 'I40' },
    {brand: 'HYUNDAI', model: 'Elantra' },
    {brand: 'HYUNDAI', model: 'I30' },
    {brand: 'HYUNDAI', model: 'Grand Santa Fe' },
    {brand: 'HYUNDAI', model: 'Genesis' },
    {brand: 'HYUNDAI', model: 'H-1 Travel' },
    {brand: 'INFINITI', model: 'Q70' },
    {brand: 'INFINITI', model: 'Q50' },
    {brand: 'INFINITI', model: 'QX70' },
    {brand: 'INFINITI', model: 'QX50' },
    {brand: 'INFINITI', model: 'Q60' },
    {brand: 'ISUZU', model: 'D-Max' },
    {brand: 'JAGUAR', model: 'XF' },
    {brand: 'JAGUAR', model: 'Serie XK' },
    {brand: 'JAGUAR', model: 'F-Type' },
    {brand: 'JAGUAR', model: 'XJ' },
    {brand: 'JAGUAR', model: 'XE' },
    {brand: 'JEEP', model: 'Grand Cherokee' },
    {brand: 'JEEP', model: 'Wrangler Unlimited' },
    {brand: 'JEEP', model: 'Cherokee' },
    {brand: 'JEEP', model: 'Wrangler' },
    {brand: 'JEEP', model: 'Renegade' },
    {brand: 'JEEP (FIAT)', model: 'Wrangler Unlimited' },
    {brand: 'JEEP (FIAT)', model: 'Wrangler' },
    {brand: 'JEEP (FIAT)', model: 'Cherokee' },
    {brand: 'KIA', model: 'Picanto' },
    {brand: 'KIA', model: 'Rio' },
    {brand: 'KIA', model: 'Sportage' },
    {brand: 'KIA', model: 'Venga' },
    {brand: 'KIA', model: 'Optima' },
    {brand: 'KIA', model: 'Cee-d' },
    {brand: 'KIA', model: 'Cee-d Sportswagon' },
    {brand: 'KIA', model: 'Carens' },
    {brand: 'KIA', model: 'Pro_cee-d' },
    {brand: 'KIA', model: 'Sorento' },
    {brand: 'KIA', model: 'Soul' },
    {brand: 'LADA', model: '4X4' },
    {brand: 'LADA', model: 'Priora' },
    {brand: 'LAMBORGHINI', model: 'Aventador' },
    {brand: 'LAMBORGHINI', model: 'Huracán' },
    {brand: 'LANCIA', model: 'Ypsilon' },
    {brand: 'LANCIA', model: 'Voyager' },
    {brand: 'LANCIA (FIAT)', model: 'Thema' },
    {brand: 'LANCIA (FIAT)', model: 'Delta' },
    {brand: 'LAND ROVER', model: 'Defender' },
    {brand: 'LAND ROVER', model: 'Discovery 4' },
    {brand: 'LAND ROVER', model: 'Range Rover' },
    {brand: 'LAND ROVER', model: 'Range Rover Evoque' },
    {brand: 'LAND ROVER', model: 'Freelander' },
    {brand: 'LAND ROVER', model: 'Range Rover Sport' },
    {brand: 'LAND ROVER', model: 'Discovery Sport' },
    {brand: 'LEXUS', model: 'GS' },
    {brand: 'LEXUS', model: 'RX' },
    {brand: 'LEXUS', model: 'CT' },
    {brand: 'LEXUS', model: 'IS' },
    {brand: 'LEXUS', model: 'NX' },
    {brand: 'LEXUS', model: 'RC' },
    {brand: 'LEXUS', model: 'LS' },
    {brand: 'MAHINDRA', model: 'XUV500' },
    {brand: 'MASERATI', model: 'GranCabrio' },
    {brand: 'MASERATI', model: 'Quattroporte' },
    {brand: 'MASERATI', model: 'Ghibli' },
    {brand: 'MASERATI', model: 'GranTurismo' },
    {brand: 'MAZDA', model: 'Mazda2' },
    {brand: 'MAZDA', model: 'CX-5' },
    {brand: 'MAZDA', model: 'Mazda6' },
    {brand: 'MAZDA', model: 'MX-5' },
    {brand: 'MAZDA', model: 'Mazda3' },
    {brand: 'MAZDA', model: 'Mazda5' },
    {brand: 'MAZDA', model: 'CX-9' },
    {brand: 'MAZDA', model: 'CX-3' },
    {brand: 'MERCEDES', model: 'Clase SL' },
    {brand: 'MERCEDES', model: 'Clase SLK' },
    {brand: 'MERCEDES', model: 'Clase V' },
    {brand: 'MERCEDES', model: 'Clase C' },
    {brand: 'MERCEDES', model: 'Clase M' },
    {brand: 'MERCEDES', model: 'Clase G' },
    {brand: 'MERCEDES', model: 'Clase E' },
    {brand: 'MERCEDES', model: 'Clase CL' },
    {brand: 'MERCEDES', model: 'Clase S' },
    {brand: 'MERCEDES', model: 'Clase S MAYBACH' },
    {brand: 'MERCEDES', model: 'Clase GLK' },
    {brand: 'MERCEDES', model: 'SLS AMG' },
    {brand: 'MERCEDES', model: 'Clase B' },
    {brand: 'MERCEDES', model: 'Clase A' },
    {brand: 'MERCEDES', model: 'Clase GL' },
    {brand: 'MERCEDES', model: 'Clase CLS' },
    {brand: 'MERCEDES', model: 'Clase CLA' },
    {brand: 'MERCEDES', model: 'Clase GLA' },
    {brand: 'MERCEDES', model: 'AMG GT' },
    {brand: 'MERCEDES', model: 'Vito' },
    {brand: 'MERCEDES', model: 'Clase GLE Coupé' },
    {brand: 'MERCEDES', model: 'Clase GLE' },
    {brand: 'MERCEDES', model: 'Clase GLE Coupé' },
    {brand: 'MINI', model: 'MINI' },
    {brand: 'MINI', model: 'COUNTRYMAN' },
    {brand: 'MINI', model: 'PACEMAN' },
    {brand: 'MITSUBISHI', model: 'Montero' },
    {brand: 'MITSUBISHI', model: 'I-MiEV' },
    {brand: 'MITSUBISHI', model: 'ASX' },
    {brand: 'MITSUBISHI', model: 'Outlander' },
    {brand: 'MITSUBISHI', model: 'Space Star' },
    {brand: 'MITSUBISHI', model: 'L200' },
    {brand: 'MORGAN', model: 'Roadster' },
    {brand: 'MORGAN', model: 'Plus 8' },
    {brand: 'MORGAN', model: 'Plus 4' },
    {brand: 'NISSAN', model: 'X-TRAIL' },
    {brand: 'NISSAN', model: 'QASHQAI' },
    {brand: 'NISSAN', model: 'NOTE' },
    {brand: 'NISSAN', model: 'LEAF' },
    {brand: 'NISSAN', model: 'Pathfinder' },
    {brand: 'NISSAN', model: 'EVALIA' },
    {brand: 'NISSAN', model: 'Navara' },
    {brand: 'NISSAN', model: 'Micra' },
    {brand: 'NISSAN', model: 'JUKE' },
    {brand: 'NISSAN', model: '370Z' },
    {brand: 'NISSAN', model: 'NV200' },
    {brand: 'NISSAN', model: 'GT-R' },
    {brand: 'NISSAN', model: 'PULSAR' },
    {brand: 'NISSAN', model: 'Murano' },
    {brand: 'OPEL', model: 'Corsa' },
    {brand: 'OPEL', model: 'Astra' },
    {brand: 'OPEL', model: 'Meriva' },
    {brand: 'OPEL', model: 'Zafira Tourer' },
    {brand: 'OPEL', model: 'Zafira' },
    {brand: 'OPEL', model: 'Insignia' },
    {brand: 'OPEL', model: 'Combo' },
    {brand: 'OPEL', model: 'Ampera' },
    {brand: 'OPEL', model: 'Mokka' },
    {brand: 'OPEL', model: 'Adam' },
    {brand: 'OPEL', model: 'Cabrio' },
    {brand: 'OPEL', model: 'Antara' },
    {brand: 'OPEL', model: 'Karl' },
    {brand: 'PEUGEOT', model: '308' },
    {brand: 'PEUGEOT', model: '807' },
    {brand: 'PEUGEOT', model: 'Bipper' },
    {brand: 'PEUGEOT', model: '508' },
    {brand: 'PEUGEOT', model: 'Partner' },
    {brand: 'PEUGEOT', model: '3008' },
    {brand: 'PEUGEOT', model: '208' },
    {brand: 'PEUGEOT', model: '2008' },
    {brand: 'PEUGEOT', model: 'RCZ' },
    {brand: 'PEUGEOT', model: '5008' },
    {brand: 'PEUGEOT', model: '4008' },
    {brand: 'PEUGEOT', model: '108' },
    {brand: 'PEUGEOT', model: '207' },
    {brand: 'PEUGEOT', model: 'Ion' },
    {brand: 'PORSCHE', model: '911' },
    {brand: 'PORSCHE', model: 'Boxster' },
    {brand: 'PORSCHE', model: 'Cayenne' },
    {brand: 'PORSCHE', model: 'Panamera' },
    {brand: 'PORSCHE', model: '918' },
    {brand: 'PORSCHE', model: 'Macan' },
    {brand: 'PORSCHE', model: 'Cayman' },
    {brand: 'RENAULT', model: 'Fluence' },
    {brand: 'RENAULT', model: 'Grand Scénic' },
    {brand: 'RENAULT', model: 'Latitude' },
    {brand: 'RENAULT', model: 'Clio' },
    {brand: 'RENAULT', model: 'Scénic' },
    {brand: 'RENAULT', model: 'Laguna' },
    {brand: 'RENAULT', model: 'Kangoo Combi' },
    {brand: 'RENAULT', model: 'Mégane' },
    {brand: 'RENAULT', model: 'Grand Kangoo Combi' },
    {brand: 'RENAULT', model: 'Captur' },
    {brand: 'RENAULT', model: 'ZOE' },
    {brand: 'RENAULT', model: 'Koleos' },
    {brand: 'RENAULT', model: 'Twingo' },
    {brand: 'RENAULT', model: 'Espace' },
    {brand: 'RENAULT', model: 'Kadjar' },
    {brand: 'ROLLS-ROYCE', model: 'Phantom' },
    {brand: 'SEAT', model: 'Ibiza' }, 
    {brand: 'SEAT', model: 'Nuevo León' }, 
    {brand: 'SEAT', model: 'Alhambra' }, 
    {brand: 'SEAT', model: 'Altea' }, 
    {brand: 'SEAT', model: 'Mii' }, 
    {brand: 'SEAT', model: 'Toledo' }, 
    {brand: 'SEAT', model: 'Altea XL' }, 
    {brand: 'SKODA', model: 'Octavia' },
    {brand: 'SKODA', model: 'Fabia' },
    {brand: 'SKODA', model: 'Roomster' },
    {brand: 'SKODA', model: 'Yeti' },
    {brand: 'SKODA', model: 'Superb' },
    {brand: 'SKODA', model: 'Citigo' },
    {brand: 'SKODA', model: 'Rapid' },
    {brand: 'SKODA', model: 'Spaceback' },
    {brand: 'SKODA', model: 'Scout' },
    {brand: 'SMART', model: 'Fortwo' },
    {brand: 'SMART', model: 'Forfour' },
    {brand: 'SSANGYONG', model: 'Rexton' },
    {brand: 'SSANGYONG', model: 'Rodius' },
    {brand: 'SSANGYONG', model: 'Korando' },
    {brand: 'SSANGYONG', model: 'Actyon Sports Pick Up' },
    {brand: 'SSANGYONG', model: 'Tivoli' },
    {brand: 'SUBARU', model: 'Forester' },
    {brand: 'SUBARU', model: 'XV' },
    {brand: 'SUBARU', model: 'Outback' },
    {brand: 'SUBARU', model: 'BRZ' },
    {brand: 'SUBARU', model: 'WRX STI' },
    {brand: 'SUZUKI', model: 'Grand Vitara' },
    {brand: 'SUZUKI', model: 'Swift' },
    {brand: 'SUZUKI', model: 'SX4' },
    {brand: 'SUZUKI', model: 'Jimny' },
    {brand: 'SUZUKI', model: 'SX4 S-Cross' },
    {brand: 'SUZUKI', model: 'Celerio' },
    {brand: 'SUZUKI', model: 'Kizashi' },
    {brand: 'SUZUKI', model: 'Vitara' },
    {brand: 'TATA', model: 'Xenon' },
    {brand: 'TATA', model: 'Aria' },
    {brand: 'TATA', model: 'Vista' },
    {brand: 'TOYOTA', model: 'Avensis' },
    {brand: 'TOYOTA', model: 'Land Cruiser' },
    {brand: 'TOYOTA', model: 'Yaris' },
    {brand: 'TOYOTA', model: 'Verso' },
    {brand: 'TOYOTA', model: 'Auris' },
    {brand: 'TOYOTA', model: 'Prius+' },
    {brand: 'TOYOTA', model: 'GT86' },
    {brand: 'TOYOTA', model: 'Prius' },
    {brand: 'TOYOTA', model: 'Rav4' },
    {brand: 'TOYOTA', model: 'Aygo' },
    {brand: 'TOYOTA', model: 'Hilux' },
    {brand: 'TOYOTA', model: 'Land Cruiser 200' },
    {brand: 'VOLKSWAGEN', model: 'Polo' },
    {brand: 'VOLKSWAGEN', model: 'Jetta' },
    {brand: 'VOLKSWAGEN', model: 'Phaeton' },
    {brand: 'VOLKSWAGEN', model: 'Golf' },
    {brand: 'VOLKSWAGEN', model: 'Touran' },
    {brand: 'VOLKSWAGEN', model: 'Touareg' },
    {brand: 'VOLKSWAGEN', model: 'Beetle' },
    {brand: 'VOLKSWAGEN', model: 'Sharan' },
    {brand: 'VOLKSWAGEN', model: 'Tiguan' },
    {brand: 'VOLKSWAGEN', model: 'Multivan' },
    {brand: 'VOLKSWAGEN', model: 'California' },
    {brand: 'VOLKSWAGEN', model: 'Caravelle' },
    {brand: 'VOLKSWAGEN', model: 'Up!' },
    {brand: 'VOLKSWAGEN', model: 'CC' },
    {brand: 'VOLKSWAGEN', model: 'Golf Sportsvan' },
    {brand: 'VOLKSWAGEN', model: 'Amarok' },
    {brand: 'VOLKSWAGEN', model: 'Caddy' },
    {brand: 'VOLKSWAGEN', model: 'Transporter' },
    {brand: 'VOLKSWAGEN', model: 'Scirocco' },
    {brand: 'VOLKSWAGEN', model: 'Passat' },
    {brand: 'VOLKSWAGEN', model: 'Eos' },
    {brand: 'VOLVO', model: 'V70' },
    {brand: 'VOLVO', model: 'S80' },
    {brand: 'VOLVO', model: 'XC70' },
    {brand: 'VOLVO', model: 'V60' },
    {brand: 'VOLVO', model: 'S60' },
    {brand: 'VOLVO', model: 'XC90' },
    {brand: 'VOLVO', model: 'XC60' },
    {brand: 'VOLVO', model: 'V40' },
    {brand: 'VOLVO', model: 'V40 Cross Country' },
    {brand: 'VOLVO', model: 'V60 Cross Country' },
    {brand: 'VOLVO', model: 'S60 Cross Country' },
    {brand: 'CADILLAC', model: 'ATS' },
    {brand: 'CADILLAC', model: 'ATS-V' },
    {brand: 'CADILLAC', model: 'CTS' },
    {brand: 'CADILLAC', model: 'CTS-V' },
    {brand: 'CADILLAC', model: 'XTS' },
    {brand: 'CADILLAC', model: 'CT6' },
    {brand: 'CADILLAC', model: 'ESCALADE / ESV' },
    {brand: 'DODGE', model: 'JOURNEY' },
    {brand: 'DODGE', model: 'AVENGER' },
    {brand: 'LINCOLN', model: 'MKZ' }, 
    {brand: 'LINCOLN', model: 'MKX' }, 
    {brand: 'LINCOLN', model: 'CONTINENTAL' }, 
    {brand: 'TESLA', model: 'MODEL S' },
    {brand: 'TESLA', model: 'MODEL X' }
    ])